name: gogreen
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.5.0
  flutter_svg: ^1.0.3  # إضافة مكتبة flutter_svg لقراءة ملفات SVG

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/img.png
    - images/img_1.png
    - images/img_2.png
    - images/img_3.png
    - images/img_4.png
    - images/img_5.png
    - images/img_6.png
    - images/img_7.png
    - images/img_9.png
    - images/img_10.png
    - images/img_11.png
    - images/img_12.png
    - images/img_13.png
    - images/img_14.png
    - images/img_15.png
    - images/img_16.png
    - images/img_17.png
    - images/img_18.png
    - images/img_19.png
    - images/img_20.png
    - images/img_21.png
    - images/img_22.png
    - images/img_23.png
    - images/img_25.png
    - images/img_26.png
    - images/img_27.png
    - images/img_28.png
    - images/img_29.png
    - images/img_30.png
    - images/img_31.png
    - images/img_32.png
    - images/img_33.png
    - images/img_34.png
    - images/img_35.png
