name: gogreen
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

flutter_native_splash:
  color: "#147351"
  image: images/img_41.png
  android: true
  ios: true
  fullscreen: true

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  iconify_flutter: ^0.0.7

  flutter_vector_icons: ^2.0.0
  carbon_icons: ^0.0.1+2
  shared_preferences: ^2.0.7
  image_picker: ^1.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.5
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.4
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.5.0
  provider: ^6.1.2
  flutter_map: ^6.0.0
  latlong2: ^0.9.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/img_48.png"
  flutter_native_splash:
  color: "#42a5f5"
  image: images/img_42.png
  android_gravity: fill

dev_dependencies:
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/img.png
    - images/img_1.png
    - images/img_2.png
    - images/img_3.png
    - images/img_4.png
    - images/img_5.png
    - images/img_6.png
    - images/img_7.png
    - images/img_8.png
    - images/img_9.png
    - images/img_10.png
    - images/img_11.png
    - images/img_12.png
    - images/img_13.png
    - images/img_14.png
    - images/img_15.png
    - images/img_16.png
    - images/img_17.png
    - images/img_18.png
    - images/img_19.png
    - images/img_20.png
    - images/img_21.png
    - images/img_22.png
    - images/img_23.png
    - images/img_25.png
    - images/img_26.png
    - images/img_27.png
    - images/img_28.png
    - images/img_29.png
    - images/img_30.png
    - images/img_31.png
    - images/img_32.png
    - images/img_33.png
    - images/img_34.png
    - images/img_35.png
    - images/img_36.png
    - images/img_37.png
    - images/img_38.png
    - images/img_39.png
    - images/img_40.png
    - images/img_41.png
    - images/img_42.png
    - images/img_43.png
    - images/img_44.png
    - images/img_45.png
    - images/img_46.png
    - images/img_48.png
    - images/img_49.png
    - images/img_50.png
    - images/img_51.png
    - images/img_52.png
    - images/img_53.png
    - images/img_54.png
    - images/imgg.png
